// Mouse location object
const mouse = { x: 0, y: 0 }

// Class for representing objects built with drag and drop
class DndNode {
    constructor(parent, type, key, value) {
        this.parent = parent
        this.type   = type
        this.key    = key
        this.value  = value
        
        this.x = mouse.x
        this.y = mouse.y

        if (this.parent != null) {
            if (this.parent.type == "object") {
                // If parent is an object, map the assigned key to this object
                this.parent.children[key] = this
            } 
            
            if (this.parent.type == "array") {
                // If parent is an array, push this element into it
                this.key = this.parent.children.length
                this.parent.children.push(this)
            }
        }
    }
}

// Handle for the rendering area
var area = null

// Current JSON tree, as generated by output
const generateJSON = {}

// Current tree of drag-and-drop objects created
const createdObjects = []